import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { GraphQLClient, gql } from 'graphql-request';
import { useState } from 'react';

const graphcms = new GraphQLClient(
  'https://api-sa-east-1.hygraph.com/v2/clbcwkx9h19zz01t914oy9q6f/master'
);

const QUERY = gql`  
  posts {
    content
    createdAt
    datePublished
    id
    publishedAt
    slug
    title
    updatedAt
    author {
      name
      avatar {
        url
      }
    }
    coverPhoto {
      publishedAt {
        createdBy {
          id
        }
        url
      }
    }
  }
`;

export default function Home() {
  const [posts, setPosts] = useState([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
}
